#!/bin/bash
# https://github.com/jorgebastida/awslogs
#
# Watches cloudwatch logs
#
# example: lgw <lambda_name> <search_term>
# example: lgw auth-service-develop-app
# example: lgw auth-service-develop-app ERROR

REGION=us-east-1

if [ -z "$2" ]
  then
    echo "No search params supplied."
    awslogs get $1 ALL --aws-region $REGION --watch    
  else
    echo "Using search param $2"
    awslogs get $1 ALL --aws-region $REGION --watch | grep $2
fi


